repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

    # ruff
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.255
    hooks:
    -   id: ruff

    # black formatter
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: # arguments to configure black
          - --line-length=88
          - --include='\.pyi?$'
          - -S

        # these folders won't be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""
        language_version: python3.11

    # mypy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
