apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: witboost-addons-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: witboost-addons-secrets
  dataFrom:
  - extract:
      key: hasura
  - extract:
        key: snowflake