apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: "hasura"
          valueMap:
            HASURA_ADMIN_SECRET: zzz
        - key: "snowflake"
          valueMap:
            SNOWFLAKE_HOST: aaa
            SNOWFLAKE_USER: bbb
            SNOWFLAKE_PASSWORD: ccc
            SNOWFLAKE_WAREHOUSE: ddd
            SNOWFLAKE_ROLE: eee