# Default values for python-specific-provisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Docker Registry Secret name used to access a private repo
dockerRegistrySecretName: regcred
# -- Allows you to specify common labels
labels: {}

image:
  # -- Image repository
  registry: registry.gitlab.com/agilefactory/witboost.mesh/provisioning/witboost.mesh.provisioning.hasuraspecificprovisioner
  # -- Image tag
  tag: 0.0.0-SNAPSHOT.71e4ae1.fix-types
  # -- The imagePullPolicy for a container and the tag of the image affect when the kubelet attempts to pull (download) the specified image.
  pullPolicy: Always

hasura:
  # -- Hasura instance URL
  url:
  # -- Hasura instance timeout
  timeout:

rolemapper:
  # -- RoleMapper microservice  URL
  url:
  # -- RoleMapper microservice  URL
  timeout:

# -- readiness probe spec
readinessProbe: {}

# -- liveness probe spec
livenessProbe: {}

# -- security context spec
securityContext:
  runAsUser: 1001
  allowPrivilegeEscalation: false
  runAsNonRoot: true

# -- resources spec
resources: {}

# -- logging override: it allows to override the content of the default logging.yaml
loggingFileOverride: {}
